development:
  app_id: 45839571943
  app_secret: c9f598f824f0b05350aac81f4c6c19b8
  callback_url: "http://proto-contractor.herokuapp.com"

production:
  app_id: 45839571943
  app_secret: c9f598f824f0b05350aac81f4c6c19b8
  callback_url: "http://proto-contractor.herokuapp.com"